import {
  Activity,
  ArrowLeft,
  Calendar,
  CalendarRange,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CloudOff,
  Dumbbell,
  Info,
  LayoutGrid,
  Minus,
  Pause,
  Play,
  Plus,
  RotateCcw,
  RotateCcwClock,
  Settings,
  Timer,
  TrendingUp,
  UserRound,
  X,
  Zap,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';

export {
  Activity,
  ArrowLeft,
  Calendar,
  CalendarRange,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CloudOff,
  Dumbbell,
  Info,
  LayoutGrid,
  Minus,
  Pause,
  Play,
  Plus,
  RotateCcw,
  RotateCcwClock,
  Settings,
  Timer,
  TrendingUp,
  UserRound,
  X,
  Zap,
};

/**
 * Set base de iconos del design system, indexado por nombre semántico del
 * dominio de entrenamiento. Todas las entradas salen del paquete instalado
 * `lucide-react-native`; el wrapper `Icon` les aplica el trazo técnico del DS.
 */
export const baseIcons = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  calendar: Calendar,
  calendarRange: CalendarRange,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  cloudOff: CloudOff,
  dumbbell: Dumbbell,
  history: RotateCcwClock,
  info: Info,
  layoutGrid: LayoutGrid,
  minus: Minus,
  pause: Pause,
  play: Play,
  plus: Plus,
  rotateCcw: RotateCcw,
  settings: Settings,
  timer: Timer,
  trendingUp: TrendingUp,
  user: UserRound,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;
