import {
  Activity,
  ArrowLeft,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CloudOff,
  Dumbbell,
  House,
  Info,
  Layers,
  Minus,
  Pause,
  Play,
  Plus,
  RotateCcw,
  ScrollText,
  Settings,
  Timer,
  TrendingUp,
  User,
  X,
  Zap,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';

export {
  Activity,
  ArrowLeft,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CloudOff,
  Dumbbell,
  House,
  Info,
  Layers,
  Minus,
  Pause,
  Play,
  Plus,
  RotateCcw,
  ScrollText,
  Settings,
  Timer,
  TrendingUp,
  User,
  X,
  Zap,
};

/**
 * Set base de iconos del design system, indexado por nombre semántico del
 * dominio de entrenamiento. Todas las entradas salen del paquete instalado
 * `lucide-react-native`; el wrapper `Icon` les aplica el trazo técnico del DS.
 */
export const baseIcons = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  calendar: Calendar,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  cloudOff: CloudOff,
  dumbbell: Dumbbell,
  house: House,
  info: Info,
  layers: Layers,
  minus: Minus,
  pause: Pause,
  play: Play,
  plus: Plus,
  rotateCcw: RotateCcw,
  scrollText: ScrollText,
  settings: Settings,
  timer: Timer,
  trendingUp: TrendingUp,
  user: User,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

/** Nombre semántico de un icono del set base, p. ej. `house` o `zap`. */
export type IconName = keyof typeof baseIcons;
