// <auto-generated />
using System;
using Barrapp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barrapp.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005222428_AddAthleteSkillProgress")]
    partial class AddAthleteSkillProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Barrapp.Domain.Athlete.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("HeightCentimeters")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainingDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKilograms")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Objectives.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Objectives", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.SkillProgress.AthleteSkillProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("AthleteSkillProgresses", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Barrapp.Domain.Athlete.AthleteProfile", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Barrapp.Domain.Athlete.Maximum", "Maximums", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExerciseCode")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Repetitions")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AthleteProfileId", "ExerciseCode");

                            b1.ToTable("Maximums", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.Navigation("Maximums");
                });

            modelBuilder.Entity("Barrapp.Domain.Objectives.Objective", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barrapp.Domain.SkillProgress.AthleteSkillProgress", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
