// <auto-generated />
using System;
using Barrapp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barrapp.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006171417_AddTrainingWeekdaysToAthleteProfile")]
    partial class AddTrainingWeekdaysToAthleteProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Barrapp.Domain.Athlete.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ArmSpanCentimeters")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightCentimeters")
                        .HasColumnType("REAL");

                    b.Property<double>("InseamCentimeters")
                        .HasColumnType("REAL");

                    b.Property<int>("TrainingDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKilograms")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Objectives.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Objectives", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Planning.Mesocycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("Status = 0");

                    b.ToTable("Mesocycles", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Sessions.SessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MesocycleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MesocycleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("ClientId IS NOT NULL");

                    b.ToTable("SessionLogs", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Sessions.SessionSuelta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Focus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionSuelta", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.SkillProgress.AthleteSkillProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("AthleteSkillProgresses", (string)null);
                });

            modelBuilder.Entity("Barrapp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Barrapp.Domain.Athlete.AthleteProfile", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Barrapp.Domain.Athlete.Maximum", "Maximums", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExerciseCode")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Repetitions")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AthleteProfileId", "ExerciseCode");

                            b1.ToTable("Maximums", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.OwnsMany("Barrapp.Domain.Athlete.TrainingWeekday", "TrainingWeekdays", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Day")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AthleteProfileId", "Day");

                            b1.ToTable("TrainingWeekdays", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.Navigation("Maximums");

                    b.Navigation("TrainingWeekdays");
                });

            modelBuilder.Entity("Barrapp.Domain.Objectives.Objective", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barrapp.Domain.Planning.Mesocycle", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barrapp.Domain.Sessions.SessionLog", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Barrapp.Domain.Sessions.SessionLogSet", "Sets", b1 =>
                        {
                            b1.Property<Guid>("SessionLogId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("SetNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Effort")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SessionLogId", "SetNumber");

                            b1.ToTable("SessionLogSets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionLogId");
                        });

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Barrapp.Domain.Sessions.SessionSuelta", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Barrapp.Domain.Sessions.SessionSueltaItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("SessionSueltaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ExerciseId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("HoldSecondsMax")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("HoldSecondsMin")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Note")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Pattern")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RepsMax")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RepsMin")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Role")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Sets")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SessionSueltaId", "Position");

                            b1.ToTable("SessionSueltaItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionSueltaId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Barrapp.Domain.SkillProgress.AthleteSkillProgress", b =>
                {
                    b.HasOne("Barrapp.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
